### ISSUE TITLE
Which UD treebanks were used for training?

### ISSUE THREAD

**Issue by zerogerc** [yzhangcs/parser#104]
Hi, I've read the following in the README:

```
The multilingual dependency parsing model, named biaffine-dep-xlmr, is trained on merged 12 selected treebanks from Universal Dependencies (UD) v2.3 dataset by finetuning [xlm-roberta-large](https://huggingface.co/xlm-roberta-large). The following table lists results of each treebank. Languages are represented by [ISO 639-1 Language Codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).
```

How could I know which treebanks were used for training and evaluation?

**Comment by yzhangcs** [comment]
@zerogerc Hi, the data used for training the model is a combination of training datasets for 12 languages selected from UD2.3.
Then the model is evaluated on their respective dev/test sets.

**Comment by zerogerc** [comment]
@yzhangcs hi, but there are several treebanks for each language. Like ewt, gum or atis for english.

**Comment by yzhangcs** [comment]
@zerogerc I just follow [this paper](https://aclanthology.org/P19-1237/) for data preprocessing, and [here](https://github.com/JT-Ushio/GNNP-CoNLL18-Dataset) is their released data.
Note that UD2.2 treebanks were adopted by the CoNLL18 shared task. Here I use UD2.3 instead.

**Comment by zerogerc** [comment]
I see, thanks for the help!
