### ISSUE TITLE
Parenthesis are not parsable

### ISSUE THREAD

**Issue by MBAnslow** [yzhangcs/parser#109]
Using predict(['This', 'is', '(not)', 'parsable', '!']) with the crf-con-en model doesn't work. I suspect you work with a parenthesis representation of the string which probably causes this conflict.

**Comment by yzhangcs** [comment]
@MBAnslow Hi, this issue has been solved by the latest commits:
```py
>>> parser.predict(['This', 'is', '(not)', 'parsable', '!'], verbose=False)[0].pretty_print()\
              TOP                       
               |                         
               S                       
  _____________|______________________   
 |             VP                     | 
 |     ________|________              |  
 NP   |                ADJP           | 
 |    |         ________|______       |  
 _    _        _               _      _ 
 |    |        |               |      |  
This  is -LRB-not-RRB-      parsable  ! 

```
Please check it out :) (see https://github.com/yzhangcs/parser/commit/fe5c20395950187989955444a72c8a0e021ee389).

**Comment by MBAnslow** [comment]
Great! Thanks for fixing this quickly!
