### ISSUE TITLE
ValueError: unknown url type: 'biaffine-sdp-roberta-en'

### ISSUE THREAD

**Issue by loganzhang1** [yzhangcs/parser#113]
Hello, thanks to your code. I want to train a Semantic Dependency Parsing Model based on my data. But when I run the following code. I met the error in title. Can you help me. Thanks. The code come from https://github.com/yzhangcs/parser/blob/main/EXAMPLES.md

`python -u -m supar.cmds.biaffine_sdp train -b -d 0 -c biaffine-sdp-roberta-en -p model  \
    --train ./mpqa/head_final/train.conllu  \
    --dev ./mpqa/head_final/dev.conllu  \
    --test ./mpqa/head_final/test.conllu  \
    --encoder=bert  \
    --bert=roberta-large  \
    --lr=5e-5  \
    --lr-rate=1  \
    --batch-size=500  \
    --epochs=10  \
    --update-steps=1`

**Comment by yzhangcs** [comment]
@loganzhang1 Hi, I didn't provide the config named `biaffine-sdp-roberta-en`.
You can use `vi-sdp-roberta-en` instead.
```py
>>> Config.load('vi-sdp-roberta-en')
encoder: bert
bert: roberta-large
n_bert_layers: 4
mix_dropout: 0.0
bert_pooling: mean
encoder_dropout: 0.1
n_edge_mlp: 600
n_pair_mlp: 150
n_label_mlp: 600
edge_mlp_dropout: 0.25
pair_mlp_dropout: 0.25
label_mlp_dropout: 0.33
interpolation: 0.1
lr: 5.0e-05
lr_rate: 1
clip: 5.0
min_freq: 7
fix_len: 20
epochs: 10
warmup: 0.1
batch_size: 500
update_steps: 1

```
Thank you.

**Comment by loganzhang1** [comment]
OK, thank you.
