### ISSUE TITLE
About training Cons parsing with PTB dataset

### ISSUE THREAD

**Issue by Quang-elec44** [yzhangcs/parser#117]
Hi, I ran this command:  python -m supar.cmds.crf_con train -b -d 0 -c crf-con-en -p model -f char, and it showed train: Dataset(n_sentences=1, n_batches=1, n_buckets=1). Then the loss value was really high. Can you tell me what is the problem? Is it necessary to download the dataset or your code will download it?

**Comment by yzhangcs** [comment]
@Quang-elec44 Yes, please check that the PTB files exist in your specified paths.

**Comment by Quang-elec44** [comment]
@yzhangcs But where can i get this file: data/ptb/train.pid
