### ISSUE TITLE
Is there a way to use `crf-con-roberta-en` with the latest version of the code?

### ISSUE THREAD

**Issue by norpadon** [yzhangcs/parser#118]
Older versions of the code have bugs in the tree construction procedure, would be nice to use the latest versions of the code since it is not trivial to backport bugfixes to 1.1.0

**Comment by yzhangcs** [comment]
Hi, thank you for your suggestions. I'm working on the version 1.2, which will come in a few months.
The new version includes many features (e.g., nmt, srl), and addresses many of the bugs identified in the current version. Kindly keep an eye out for this :)
