### ISSUE TITLE
使用biaffine训练中文数据的句法分析时报错

### ISSUE THREAD

**Issue by fangfang123gh** [yzhangcs/parser#121]
您好，当我使用命令
`python -m supar.cmds.biaffine_dep train -b -d 0 -c biaffine-dep-zh -p model -f char --train data/BC-train.conllx --dev data/hlt-cdt-dev.conllx --test data/hlt-cdt-test.conllx --embed data/giga.100.txt --unk ' ' `
训练中文数据的biaffine句法分析模型时，出现了以下错误：
`ValueError: tuple.index(x): x not in tuple`
可以问一下我该怎么解决这个问题吗？

**Comment by yzhangcs** [comment]
@fangfang123gh 你好，可以参考#19，另外建议代码更新到最新

**Comment by fangfang123gh** [comment]
好的 谢谢你！
