### ISSUE TITLE
如何下载dep-biaffine-xlmr的checkpoint？

### ISSUE THREAD

**Issue by Dereck0602** [yzhangcs/parser#122]
import torch
from supar import Parser

torch.cuda.set_device('cuda:0')
parser = Parser.load('dep-biaffine-xlmr')

![微信截图_20230512115258](https://github.com/yzhangcs/parser/assets/52696292/3091697a-37af-40cc-bd7f-e0846a8d6c13)

**Comment by yzhangcs** [comment]
@Dereck0602 Hi, 我试了下是可以load的
<img width="1044" alt="image" src="https://github.com/yzhangcs/parser/assets/18402347/e73b07c5-42bc-45f3-87d8-3bc12445649d">
请确保代码是最新commit

**Comment by Dereck0602** [comment]
感谢！已解决

**Comment by Hairmore** [comment]
> 感谢！已解决

请问是如何解决的呀？我下载的最新代码，但是也遇到这个问题

**Comment by xiaoAugenstern** [comment]
请问是如何解决的呀？我下载的最新代码，但是也遇到这个问题，我也是

**Comment by xiaoAugenstern** [comment]
parser = Parser.load('biaffine-dep-xlmr',reload=True)
dataset = parser.predict('Ich habe viele Lieblingsbänder.', lang='de', prob=True, verbose=False)
好像要这样才能下载


> > 感谢！已解决
> 
> 请问是如何解决的呀？我下载的最新代码，但是也遇到这个问题
