### ISSUE TITLE
'con-crf-roberta-en' won't load 

### ISSUE THREAD

**Issue by dslim23** [yzhangcs/parser#123]
- Python version: 3.10
- Operating System: 13.3.1 

### Description

I was trying to load a model using `Parser.load('con-crf-roberta-en')` and predict on a sentence, but I encountered a ValueError saying "unknown url type: 'con-crf-roberta-en".

This error occurred running your code snippet in README.md: 

```python
from supar import Parser
 
parser = Parser.load('con-crf-roberta-en')

dataset = parser.predict('I saw Sarah with a telescope.', lang='en', prob=True, verbose=False)
```

**Comment by dslim23** [comment]
upon a bit of investigation, it seems like the models here http://hlt.suda.edu.cn/~yzhang/supar/v1.1.0/ptb.crf.con.roberta.zip aren't accessible (perhaps due to server overload)

**Comment by yzhangcs** [comment]
@dslim23 Hi, you might need to install supar from source code
```sh
pip install -U git+https://github.com/yzhangcs/parser
```

**Comment by dslim23** [comment]
I got it working with your suggestion thank you! is this still an issue https://github.com/yzhangcs/parser/issues/118#issuecomment-1431639685? I would like to use the pretrained weights

**Comment by yzhangcs** [comment]
@dslim23 Hi, I've submitted some patches, so installing from source are ok for RoBERTa :-)

**Comment by Quang-elec44** [comment]
@yzhangcs Hi, can you check the again since I coudn't download this checkpoint?
