### ISSUE TITLE
low performance of  "dep-biaffine-xlmr"?

### ISSUE THREAD

**Issue by cyr19** [yzhangcs/parser#124]
hi,

thanks for your great work!

I tried to use the xlmr model for dependency parsing on German texts, but the results didn't make sense at all.
#### text = "Es ist ein einfacher Satz."
1       Es      _       _       _       _       6       nmod    _       _
2       ist     _       _       _       _       6       flat    _       _
3       ein     _       _       _       _       6       flat    _       _
4       einfacher       _       _       _       _       6       nmod    _       _
5       Satz    _       _       _       _       6       appos   _       _
6       .       _       _       _       _       0       root    _       _

So I further evaluated it on the UD German treebank, which also only led to unreasonable results.

loss: 9.8960 - UCM:  1.33% LCM:  0.61% UAS:  4.18% LAS:  0.58%

The parsing results on English sent were also like this:
#### text = "It is a simple sentence."
1       It      _       _       _       _       6       appos   _       _
2       is      _       _       _       _       6       appos   _       _
3       a       _       _       _       _       6       appos   _       _
4       simple  _       _       _       _       6       nmod    _       _
5       sentence        _       _       _       _       6       appos   _       _
6       .       _       _       _       _       0       root    _       _

So I wonder if it would be possible that this checkpoint is not the one you evaluated on the UD treebanks? Could you maybe run it on the above examples if your time permits?  

Thanks a lot!

Best, 
YC

**Comment by yzhangcs** [comment]
@cyr19 Hi, thank you for reporting this. I'm not sure what exactly happened. Possible causes are `transformers` version/weight mismatch. I'll retrain the model and upload it recently, please stay tuned!

**Comment by yzhangcs** [comment]
@cyr19 the file has been updated, please check it out :)

**Comment by cyr19** [comment]
Hi, thanks for your quick response! I was off github.

The whole lib doesn't work now as i switched to another environment. I'm not sure where it results: the current error log is "ModuleNotFoundError: No module named 'supar.config'". Could you help me with this?
![image](https://github.com/yzhangcs/parser/assets/87754318/c3a69011-0832-4b52-b255-427eff4506ac)

Thanks a lot :)

**Comment by yzhangcs** [comment]
@cyr19 The config has been moved to other places, you may need to install supar from source code.
