### ISSUE TITLE
How to using checkpoint to predict

### ISSUE THREAD

**Issue by Dive-to-OCR** [yzhangcs/parser#125]
I try training model by command like
```python
!python -u -m supar.cmds.dep.biaffine train -b -d 0 -c dep-biaffine-en -p model -f bert  \
    --train Data/content/VnDep/Train/[VnDep]Train_Mau.conllu  \
    --dev Data/content/VnDep/Dev/[VnDep]Dev_25283.conllu  \
    --test Data/content/VnDep/Test/[VnDep]Test_25272.conllu  \
    --bert bert-base-multilingual-cased 
```
and i get 3 files:
```python
model
model.train.log
model.ymal
```

But i don't know load this model to predict. Can you help me?

**Comment by yzhangcs** [comment]
@Dive-to-OCR Hi, you can make predictions by `python -u -m supar.cmds.dep.biaffine predict -p model` or from cmd line `Parser.load('model').predict(...)`. Please check [README](https://github.com/yzhangcs/parser/blob/main/README.md) and [examples](https://github.com/yzhangcs/parser/blob/main/examples) for details.
