### ISSUE TITLE
需要您的帮助

### ISSUE THREAD

**Issue by Lj4040** [yzhangcs/parser#126]
您好，我在其他论文中看到了您的工作，觉得您的工作非常棒！对此非常感兴趣，我想问您几个问题，如果我想用您的解析器parser = Parser.load('dep-biaffine-en')这样的，解析我自己的数据，我是否需要重新在我的数据上进行解析，我简单举了几个例子，我发现有的句子解析的也还行，有的解析的有偏差。还有我看您给的例子当中，可以选择分词，也可以选择不分词进行解析，是否分词解析的结果是更好？

**Comment by yzhangcs** [comment]
@Lj4040 感谢青睐
> 我是否需要重新在我的数据上进行解析，我简单举了几个例子，我发现有的句子解析的也还行，有的解析的有偏差

需要parse一下，保证效果可以使用roberta模型

> 可以选择分词，也可以选择不分词进行解析，是否分词解析的结果是更好

不tokenize输入的话会采用stanza进行内部tokenize，如果自己有gold分词结果当然是gold的效果更好

**Comment by Lj4040** [comment]
好的非常感谢您的回复‘！

**Comment by Lj4040** [comment]
您说的parser就是指的parser.predict（句子）把？，使用的是中文，我看见中文好像没有roberta，最好的好像就是这个dep-biaffine-electra-zh。

**Comment by yzhangcs** [comment]
是的，electra是目前已有最佳的

**Comment by Lj4040** [comment]
非常感谢您的回答
