### ISSUE TITLE
Necessity to create a new release

### ISSUE THREAD

**Issue by davebulaval** [yzhangcs/parser#128]
Hi, I have noticed that the doc (i.e. README) and super.NAME has changed compared to the release 1.1.4. This leads to an error when loading the model if you don't use the previous file's name structure (model-con-en).

See commit abb5623.

**Comment by yzhangcs** [comment]
@davebulaval Hi, currently it's recommended to directly install v1.1.4 if you wish to use weights  of v1.1.0.
And which model you failed to load? I've tried `con-crf-en`, it seems ok?

**Comment by davebulaval** [comment]
My point was that the code in the main branch differs from the one in release 1.1.4, so by using the documentation in the readme, the models' names are not the same as the ones used in the release code.

For example, in the code of release 1.1.4, the model names are written as `crf-con-en` (see the picture as proof), while the README rather uses the format `con-crf-en`. This, it is **really** confusing.

![image](https://github.com/yzhangcs/parser/assets/24845694/89bd5a97-634c-44cc-a8cf-3506fe547807)


Moreover, release 1.1.4 **does not** include the weights. The last release with weights is 1.1.0 (also reflected in the download URL in the code base) -> 

```
SRC = {'github': 'https://github.com/yzhangcs/parser/releases/download',
       'hlt': 'http://hlt.suda.edu.cn/~yzhang/supar'}
[...]
MODEL = {src: {n: f"{link}/v1.1.0/{m}.zip" for n, m in NAME.items()} for src, link in SRC.items()}
CONFIG = {src: {n: f"{link}/v1.1.0/{m}.ini" for n, m in NAME.items()} for src, link in SRC.items()}
```

**Comment by yzhangcs** [comment]
@davebulaval There are many commits since v1.1.4, so it would be better to install the pkg from source if you wish to use many new features like attach-juxtapose parser. I think the docs are more aligned with the newest commits If I haven't forgotten to update. 

I'll take some time to create a new release to accommodate those many changes and clarify potential mismatches. Thank you!

**Comment by davebulaval** [comment]
If you want, I have `.github` action for GitHub runner to automatically create a release. I can open a PR to help.

**Comment by davebulaval** [comment]
@yzhangcs, do you plan to make a release regarding my points? It would be easier for me to use your package in another package.

**Comment by yzhangcs** [comment]
@davebulaval Thank you for your concern, promise to make a new release this month :-D
