### ISSUE TITLE
Missing AttachJuxtapose pre-trained weights

### ISSUE THREAD

**Issue by davebulaval** [yzhangcs/parser#129]
Hi, I've been looking in the code, and the official weights release (https://github.com/yzhangcs/parser/releases/v1.1.0), and I cannot find the AttachJuxtapose pre-trained weights.

Are they available somewhere else?

**Comment by yzhangcs** [comment]
@davebulaval Hi, now I have no plan to release the pre-trained weights of AttachJuxtapose parser as it performs similarly to crf, but uses more storage space. So if you do need this, you may need to train it by yourself :(

**Comment by davebulaval** [comment]
Ok, it would be more clear to integrate an error message if someone is trying to use this model without the weights. For now, the approach returns the model name, and the error is raised by request rather than a more verbose error.

**Comment by yzhangcs** [comment]
Thank you for your suggestion, I will add more info on available pretrained models in the near future :)
