### ISSUE TITLE
Partial Parsing

### ISSUE THREAD

**Issue by James-Decatur** [yzhangcs/parser#130]
Hello,

I've noticed that you have partial training and partial evaluation, but not partial prediction. I have a treebank/corpus with partially completed trees, with labels and arcs I know are right, and I want the parser to work from there and predict the rest. Is this possible?

Thanks,
James

**Comment by yzhangcs** [comment]
@James-Decatur Hi, it's indeed possible. You just need to populate the scores of incorrect arcs/rels with `-INF`.
Unfortunately, I can't add this to the pkg for the consistency of API interfaces (we can't access the gold annotations during prediction). You can impl it by yourself with just a few lines of code :)

**TIPS**: you could still get partial annotated rels by `[self.REL.vocab[rel] for rel in batch.sentences[0].rels]` and the same applies to arcs.

**Comment by James-Decatur** [comment]
Hey, thank you for your response! I put this project down in favor of coursework. Um, I'm having trouble implementing the change. 

"You can impl it by yourself with just a few lines of code :)" - Any chance you could give me the code? Or tell me what I'm looking for? 

Sorry and thanks,
James

**Comment by James-Decatur** [comment]
Hello again,

I'm having the hardest of time figuring out how to pass the gold annotations to the Training and Prediction processes. Can you tell me where the parameters that are getting passed to Eval, Training, and Prediction are coming from? I just want to give them everything and go from there.

parser/supar/models/dep/biaffine/parser.py

def pred_step(self, batch: Batch) -> Batch:
     words, _, *feats, arcs, rels = batch

**Comment by James-Decatur** [comment]
Nevermind,

I figured it all out.
