### ISSUE TITLE
Constituency CRF RoBERTa English not working properly

### ISSUE THREAD

**Issue by SirBernardPhilip** [yzhangcs/parser#131]
I am trying to run the constituency parser using the pretrained RoBERTa English model but it does not do a good job of parsing sentences. The "con-crf-en" model works as expected but the RoBERTa one fails to properly parse any sentences and outputs something like this every time:
```
>>> parser.predict(['I', 'saw', 'Sarah', 'with', 'a', 'telescope', '.'], verbose=False, prob=True)[0].pretty_print()
              TOP                   
               |                     
               S                    
  _____________|__________________   
 |   |    |    |    |      |      NP
 |   |    |    |    |      |      |  
 _   _    _    _    _      _      _ 
 |   |    |    |    |      |      |  
 I  saw Sarah with  a  telescope  . 
```

Here's a [notebook link](https://colab.research.google.com/drive/1dShXNI2NcOvbLhwBisV-tOt3iD7luYir?usp=sharing) that replicates the issue

**Comment by yzhangcs** [comment]
@SirBernardPhilip Hi, the previous weights were corrupted somehow. I've uploaded the re-trained model. Please check it out :)

**Comment by SirBernardPhilip** [comment]
Amazing thank you! I just checked and the new model works for English. Also, the same thing is happening for the `con-cr-xlmr` model:
```
>>> from supar import Parser
>>> model_name = "con-crf-xlmr"
>>> parser = Parser.load(model_name)
>>> parser.predict(['Je', 'ai', 'vu', 'Sarah', 'avec', 'un', 'télescope', '.'], verbose=False, prob=True)[0].pretty_print()
             TOP                        
              |                          
              S                         
  ____________|_______________________   
 _   _   _    _    _    _      _      _ 
 |   |   |    |    |    |      |      |  
 Je  ai  vu Sarah avec  un télescope  . 

```
