### ISSUE TITLE
Submodule not found

### ISSUE THREAD

**Issue by amunozo** [yzhangcs/parser#133]
Hi. I'm keep getting this error after installing it.

Error while finding module specification for 'supar.cmds.dep.biaffine' (ModuleNotFoundError: No module named 'supar.cmds.dep')

What I am trying to run is this:
```
CUDA_VISIBLE_DEVICES="1"  python3 -u -m supar.cmds.dep.biaffine train -b -d 0 -c deep-biaffine-xmlr -p model -f char        
 --train ud-treebanks-v2.12/UD_Spanish-AnCora/es_ancora-ud-train.conllu        
 --dev ud-treebanks-v2.12/UD_Spanish-AnCora/es_ancora-ud-dev.conllu         
--test ud-treebanks-v2.12/UD_Spanish-AnCora/es_ancora-ud-test.conllu        
 --encoder=bert        
 --bert=xml-roberta-large         
--lr=5e-05         
--lr-rate=20         
--epochs=10         
--update_steps=4

```

Thanks

**Comment by yzhangcs** [comment]
Hi, did you install supar from source? Please make sure the path `supar/cmds/dep` exists. The module structures have been largely changed since v1.1.4.
