### ISSUE TITLE
Unable to use "biaffine-dep-roberta-en"

### ISSUE THREAD

**Issue by Hawkwoodd** [yzhangcs/parser#134]
I downloaded ptb.biaffine.dep.roberta from releases, but when using it, I reported the following error: "ModuleNotFoundError: No module named 'sub. config'". However, there were no issues with using ptb.biaffine.dep.lstm.char

**Comment by yzhangcs** [comment]
@Hawkwoodd Hi, this example works well for me 
https://colab.research.google.com/drive/16qx933DqlE5iNDUo41J0MVKOJKNTCmWf?usp=sharing
Please follow the snippets and let me know if there are still errors :)
