### ISSUE TITLE
AttributeError: 'BertTokenizerFast' object has no attribute 'split_special_tokens'

### ISSUE THREAD

**Issue by muhammed-abuodeh** [yzhangcs/parser#142]
After installing newers versions of torch and transformers (2.2.2 and 4.43.4, respectively), I've been receiving the error
`AttributeError: 'BertTokenizerFast' object has no attribute 'split_special_tokens'`

I tried installing from source, no luck. the error is raised after I load a model and then predict:
```
parser = Parser.load(parse_model)
return parser.predict(conll_path_or_parsed_tuples, verbose=False, tree=True, proj=True)
```
My code worked when using an older version of supar (commit 17ec77dd), however I am forced to upgrade dependencies in my codebase, causing an issue with supar.

python version: 3.11.3

Thanks!

**Comment by svenha** [comment]
Can you show the source context of the error line? In some cases, it suffices to set `split_special_tokens=False`
