### ISSUE TITLE
Decode with MST algorithm

### ISSUE THREAD

**Issue by allanj** [yzhangcs/parser#18]
I agree that using Eisner's algorithm can have better results for projective dependency parsing.  If MST is supported, it would be great.

**Comment by zysite** [comment]
Thanks for your advice.
But implementing a batchified version of MST algorithm (Chu-Liu/Edmods and Tarjan) is a challenging task for me. I will try to complete this in my free hours. 
If you have a need for MST, I think the official implementation, though implemented by TF,  is a good reference.

**Comment by yzhangcs** [comment]
@allanj Hi, the code for MST decoding has be added.
