### ISSUE TITLE
token 

### ISSUE THREAD

**Issue by attardi** [yzhangcs/parser#33]
We need to use a defaultdict in biaffine_parser.py

                if hasattr(tokenizer, 'vocab'):
                    FEAT.vocab = tokenizer.vocab
                else:
                    from collections import defaultdict
                    FEAT.vocab = defaultdict(lambda: tokenizer.unk_token_id,
                                             {tokenizer._convert_id_to_token(i): i for i in range(len(tokenizer))})

because I run into a token which is split like this
['▁http', '://', 'www', '.', 'ib', 'rae', '.', 'ac', '.', 'ru', '/', 'ib', 'rae', '/', 'eng', '/', 'cher', 'no', 'by', 'l', \
'/', 'nat', '_', 're', 'p', '/', 'nat', '_', 're', 'pe', '.', 'ht', 'm', '#', '24']

and '_' is not present in the vocabulary.

**Comment by yzhangcs** [comment]
Yes, you are right. I didn't meet this since the code is only tested on BERT.

**Comment by attardi** [comment]
The defaultdict class cannot be pickled, therefore a more complex solution is needed.

Define a static class within BiaffineParser

    class FieldVocab(dict):
        """Surrogate for missing vocab in certain Transformers tokenizers."""
        def __init__(self, items, unk_token_id):
            super(BiaffineParser.FieldVocab, self).__init__(items)
            self.unk_token_id = unk_token_id

        def __getitem__(self, tok):
            return super(BiaffineParser.FieldVocab, self).get(tok, self.unk_token_id)

and the use it:

		if hasattr(tokenizer, 'vocab'):
                    FEAT.vocab = tokenizer.vocab
                else:
                    FEAT.vocab = BiaffineParser.FieldVocab(
                        {tokenizer._convert_id_to_token(i): i
                         for i in range(len(tokenizer))},
			tokenizer.unk_token_id)

**Comment by yzhangcs** [comment]
The `utils.vocab.Vocab` works for pickle

**Comment by attardi** [comment]
Yes, maybe because it is not local?
I was getting this error

AttributeError: Can't pickle local object 'BiaffineParser.build.<locals>.defaultdict'

**Comment by attardi** [comment]
Maybe is cleaner to add the class to utils/vocab.py:

    class FieldVocab(dict):
       """Surrogate for missing vocab in certain Transformers tokenizers."""
       def __init__(self, items, unk_token_id):
           super(FieldVocab, self).__init__(items)
           self.unk_token_id = unk_token_id
    
       def __getitem__(self, tok):
           return super(FieldVocab, self).get(tok, self.unk_token_id)

and import it in biaffine_parser.py:

    from supar.utils.vocab import FieldVocab

and use it like this:

                    FEAT.vocab = FieldVocab(tokenizer.unk_token_id,
                                            {tokenizer._convert_id_to_token(i): i
                                             for i in range(len(tokenizer))})

**Comment by yzhangcs** [comment]
I think it may be more elegant to integrate it into `Vocab`.

**Comment by attardi** [comment]
OK.

BTW. There are problems with the use of param n_bert_layer = 0

At least you must change:

     self.scalar_mix = ScalarMix(self.n_layers, dropout)

in BertEmbedding.__init__()

**Comment by attardi** [comment]
OMG.
In biaffine_parser.py, method build(), revert to

		FEAT = SubwordField('bert',
	                            pad=tokenizer.pad_token,
                                    unk=tokenizer.unk_token,
                                    bos=tokenizer.cls_token, # bos_token is None                            
                                    fix_len=args.fix_len,
                                    tokenize=tokenizer.tokenize)

Since WORD is created with bos set to the constant '<bos>', it caused the vectors of words and feats to have different length.

I spent all afternoon chasing this bug.

**Comment by yzhangcs** [comment]
Please pull the update. The cls_token has been replaced.

張宇
Soochow University

________________________________

**Comment by yzhangcs** [comment]
Hi, the bug is fixed right now. I have tested it on `BERT`, `XLNet` and `RoBERTa`.
Maybe you can try it out.
BTW, why did you add this line
```
args.feat_pad_index = FEAT.pad_index
```
in your pull request?
