### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

### ISSUE THREAD

**Issue by Mohd-Misran** [yzhangcs/parser#37]
I loaded the **crf-con-en** model to the Parser. Then I tried to use the **predict()** function on a list of English tokens.
But I get the above error. Need help on how to debug this!

**Here's my code:**

`from supar import Parser`
`import nltk`

`parser = Parser.load("crf-con-en")`

`text = nltk.word_tokenize("John, who is the CEO of a company, played golf.")`

`output = parser.predict(data=[text], verbose=False)`

**Complete error log:**

AttributeError                            Traceback (most recent call last)
<ipython-input-23-1e2432e7973d> in <module>
----> 1 output = parser.predict(data=[text], verbose=False)

~\anaconda3\lib\site-packages\supar\parsers\crf_constituency.py in predict(self, data, pred, buckets, batch_size, prob, mbr, verbose, **kwargs)
    121         """
    122 
--> 123         return super().predict(**Config().update(locals()))
    124 
    125     def _train(self, loader):

~\anaconda3\lib\site-packages\supar\parsers\parser.py in predict(self, data, pred, buckets, batch_size, prob, **kwargs)
    120     def predict(self, data, pred=None, buckets=8, batch_size=5000, prob=False, **kwargs):
    121         args = self.args.update(locals())
--> 122         init_logger(logger, verbose=args.verbose)
    123 
    124         self.transform.eval()

~\anaconda3\lib\site-packages\supar\utils\logging.py in init_logger(logger, path, mode, level, handlers, verbose)
     28                         level=level,
     29                         handlers=handlers)
---> 30     logger.setLevel(logging.INFO if is_master() and verbose else logging.WARNING)
     31 
     32 

~\anaconda3\lib\site-packages\supar\utils\parallel.py in is_master()
     33 
     34 def is_master():
---> 35     return not dist.is_initialized() or dist.get_rank() == 0

AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

**Comment by yzhangcs** [comment]
Hi, thanks for reporting this error.
Could you provide the pytorch version and device info.

Yu Zhang
Soochow University

________________________________

**Comment by Mohd-Misran** [comment]
@yzhangcs 

Torch version 1.5.1
Windows 10 Pro

**Comment by yzhangcs** [comment]
@Mohd-Misran You could check if `torch.distributed.is_available()` is `True` (https://github.com/facebookresearch/maskrcnn-benchmark/issues/280#issuecomment-447708949).

**Comment by Mohd-Misran** [comment]
@yzhangcs 
`torch.distributed.is_available()` is `False`

**Comment by yzhangcs** [comment]
@Mohd-Misran It seems that distributed training is not supported on Windows.

**Comment by yzhangcs** [comment]
@Mohd-Misran DDP on windows is supported on Windows since torch 1.7.
