### ISSUE TITLE
config.ini is not work for n_embed

### ISSUE THREAD

**Issue by yuxiazff** [yzhangcs/parser#39]
I have change "n_embed" in config.ini from 100 to 300，but when i run biaffine.dependency with the embedding file "sgns.renmin.word"（the size of embeddings in "sgns.renmin.word" is 300), the programe report an error. when i debug, i find "n_embed" in "models/dependncy" is still 100, it have not change to 300!!!!    that means,  "n_embed" in the programe  can not change according  to "config.ini".   so i have to change "n_embed" in "models/dependncy" to 300 by hand.

**Comment by yzhangcs** [comment]
Seems that the setting is suppressed by argparse args.
I'm working to provide a more appropriate way to deal with default settings.

**Comment by yuxiazff** [comment]
ok, i get it.

**Comment by yuxiazff** [comment]
I am sorry, it's my fault, i didn't appended the param "-c config.ini" when i trainned the model.
