### ISSUE TITLE
!pip install supar failing on Google Colab notebook

### ISSUE THREAD

**Issue by Mohd-Misran** [yzhangcs/parser#40]
I tried importing supar on Google Colab notebook using the following line of code:

`import supar`

But it threw a **ModuleNotFoundError**
So I tried installing it using `!pip install supar` and I got the following error:

**ERROR: Could not find a version that satisfies the requirement supar (from versions: none)
ERROR: No matching distribution found for supar**

@yzhangcs Can this package be used on Google Colab?

**Comment by yzhangcs** [comment]
Yes. But I haven't figure out the question yet. You can install it from source instead.

**Comment by Mohd-Misran** [comment]
@yzhangcs 
How do I install from source?

**Comment by yzhangcs** [comment]
```sh
!git clone https://github.com/yzhangcs/parser && cd parser
!python setup.py install
```

**Comment by yzhangcs** [comment]
Sorry, not working too.
Only training is supported on CoLab and it raises errors when loading `supar`.
