### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by attardi** [yzhangcs/parser#45]
Values in a config file which are also CLI arguments are discarded, since class Config overwrites those values from kwargs.

Is this intended?

The alternative is to set their default to config.SUPPRESS, like this:

    subparser.add_argument('--n-word-embed', default=argparse.SUPPRESS, type=int, help='dimension of embeddings')
    subparser.add_argument('--bert', default=argparse.SUPPRESS, help='which bert model to use')

If not specified in the CLI, they will get a default value from function call to train()

**Comment by yzhangcs** [comment]
@attardi 
Sorry for my late reply.
> Is this intended?
Yeah, it is an expected behaviour.
> The alternative is to set their default to config.SUPPRESS, like this:
That's really a good solution. I never knew the usage before. Thank you!
