### ISSUE TITLE
Data share

### ISSUE THREAD

**Issue by YuxianMeng** [yzhangcs/parser#49]
Hi, I'm very interested in your nice work, and I'd love to build my new model upon yours. 
Could you please share the conllx style data you used to reproduce your results in paper?
Looking forward to your reply~

**Comment by yzhangcs** [comment]
Hi, thanks for your interest :).
You can download the data from this [link](https://github.com/mitchellstern/minimal-span-parser/tree/master/data).

**Comment by YuxianMeng** [comment]
> Hi, thanks for your interest :).
> You can download the data from this [link](https://github.com/mitchellstern/minimal-span-parser/tree/master/data).
> The Stanford Parser v3.3.0 is needed to convert the raw pid data into conllx format. Please refer to the Biaffine Parser paper or Chen et al. 2015 (Fast and Accurate ...) for more details.

Thanks for your immediate reply! However, some links in Chen's paper is invalid, I'd greatly appreciate it if you can provide a copy of preprocessed data.

**Comment by yzhangcs** [comment]
> > Hi, thanks for your interest :).
> > You can download the data from this [link](https://github.com/mitchellstern/minimal-span-parser/tree/master/data).
> > The Stanford Parser v3.3.0 is needed to convert the raw pid data into conllx format. Please refer to the Biaffine Parser paper or Chen et al. 2015 (Fast and Accurate ...) for more details.
> 
> Thanks for your immediate reply! However, some links in Chen's paper is invalid, I'd greatly appreciate it if you can provide a copy of preprocessed data.

You can follow the instructions [here](https://github.com/hankcs/TreebankPreprocessing).
