### ISSUE TITLE
Question about fine-tuning

### ISSUE THREAD

**Issue by zerogerc** [yzhangcs/parser#53]
Hi, thanks for the awesome library. I wonder if it is possible to pretrain the model on one dataset and then fine-tune on another?

**Comment by yzhangcs** [comment]
@zerogerc you can achieve this by passing 'requires_grad=True' when initializing the BertEmbedding.
However, the code for a model without LSTM layers/word embeddings is not integrated into the repo yet. 
I'm working on this, and it can be available in the next release.

**Comment by zerogerc** [comment]
Thanks!
