### ISSUE TITLE
an error caused by brackets

### ISSUE THREAD

**Issue by LTEnjoy** [yzhangcs/parser#59]
Hi, I ran into an error when ran the code:
words = ['(', 'There', 'is', 'no', 'doubt', ')'] and I got the error as follow:
**_IndexError: list index out of range_**
What is mystrious is that when I deleted the brackets '(' and ')', it worked.
Could you tell me how can I rewrite the code to make it work even with brackets?

**Comment by yzhangcs** [comment]
@LTEnjoy It's a bug of NLTK. A way is to replace the  brackets with other symbols  like '['/']'.
