### ISSUE TITLE
unknown `lbp`

### ISSUE THREAD

**Issue by Spico197** [yzhangcs/parser#60]
Maybe the `self.model.lbp()` should be `self.model()` instead? I searched the whole projects and didn't find a model with `lbp` attribute or method. Is it a bug here ?

https://github.com/yzhangcs/parser/blob/1dce1b881f014fc265c90e6ad10781d748c56f3d/supar/parsers/semantic_dependency.py#L407

**Comment by yzhangcs** [comment]
@Spico197 Should be `self.model.vi`. Sorry for wrong name.

**Comment by Spico197** [comment]
Thx for your reply.
