### ISSUE TITLE
Constituent parsing with Chinese

### ISSUE THREAD

**Issue by Fantabulous-J** [yzhangcs/parser#66]
Hi! Can you show me an example of how to do constituent parsing over Chinese sentences with gold word segmentation available?

**Comment by yzhangcs** [comment]
@Fantabulous-J Hi, here is a toy example (electra model is available at dev branch now):
```py
>>> parser = Parser.load('crf-con-electra-zh')
>>> parser.predict([['上海', '浦东', '开发', '与', '法制', '建设', '同步']],verbose=False,lang=None).sentences[0]
( (IP (NP (NP (_ 上海) (_ 浦东)) (NP (_ 开发))) (_ 与) (NP (_ 法制) (_ 建设)) (VP (_ 同步))))
```

**Comment by Fantabulous-J** [comment]
Figured it out yesterday. But anyway, thanks a lot!
