### ISSUE TITLE
params from config.ini overridden by defaults

### ISSUE THREAD

**Issue by attardi** [yzhangcs/parser#68]
I have a config.ini file that contains:

    [Data]
    encoder = 'bert'

but when calling the parser with -c=config.ini, it gets overwritten by the default value 'lstm'.
I would expect that values provided through config.ini would replace the defaults, or else I don't see the point of providing a config file.

**Comment by yzhangcs** [comment]
@attardi Sorry there may be some confusion.
You still have to provide some values on command-line.
The priority is: argparse > config.ini > others.
config.ini provides many default hyperparams for training, which are usually not changed. 
argparse gives you more flexible choices. You can specify some params on command-line not registered in argparse but stored in config file.

**Comment by attardi** [comment]
Then why do you specify

    [Data]
    encoder = 'bert'

in ud.biaffine.dep.xlmr.ini?

**Comment by yzhangcs** [comment]
Because I forgot to delete them from argparse 😓 .

**Comment by attardi** [comment]
There are three types of defaults:

1. command line
2. config
3. function parameter defaults

To me this would be the most sensible priority order.

**Comment by yzhangcs** [comment]
Indeed many args in config are useless,  just suggestions for appropriate ones.

**Comment by attardi** [comment]
The logic of a config file is to collect in one place all parameters needed in an experiment.
They should override the defaults.
You may then individually override some of them on the command line, as a last minute minor variation.
In your interpretation, you might just as well get rid of the config file, since it is useless.

**Comment by attardi** [comment]
> The priority is: argparse > config.ini > others.

It seems to me that currently the priority is:
argparse > default parameters > config

since in config.py you do:

        config.read(conf if not conf or os.path.exists(conf) else download(supa\
r.CONFIG.get(conf, conf)))
        config = dict((name, literal_eval(value))
                      for section in config.sections()
                      for name, value in config.items(section))
        if unknown is not None:
            parser = argparse.ArgumentParser()
            for name, value in config.items():
		parser.add_argument('--'+name.replace('_', '-'), type=type(valu\
e), default=value)
            config.update(vars(parser.parse_args(unknown)))
	config.update(kwargs)

hence the kwargs override the config values.

**Comment by yzhangcs** [comment]
@attardi Yeah, but I think it's trivial to register many params like `lr`, `epochs` in argparse.
