### ISSUE TITLE
Issue with pretty_print in Constituency parser

### ISSUE THREAD

**Issue by emadg** [yzhangcs/parser#70]
Hi,

I tried your demo on your github to create constituency parser but could not get the pretty_print tree structure.

```
sent = "This is my sentence to be parsed with SuPar !"

parse = con.predict(sent.split(), verbose=False)

print(parse[0])

parse[0].pretty_print()
```

got this error:

AttributeError in python

Here is a Google colab to try and reproduce the problem: (check Issue # 1)
https://colab.research.google.com/drive/1CDZRPab8P4ba7amPxy5jhY6mBrdJ54B4?usp=sharing

**Comment by yzhangcs** [comment]
@emadg Hi, `pretty_print` has not been included in the new release.

**Comment by emadg** [comment]
@yzhangcs thanks for your response, will the function be added again or is it removed from the library for some reason?

**Comment by yzhangcs** [comment]
@emadg It has been added in v1.1.1

**Comment by emadg** [comment]
@yzhangcs Yes I confirmed that, thanks!

**Comment by emadg** [comment]
@yzhangcs Yes I confirmed that, thanks!
