### ISSUE TITLE
con.py is not available in Windows, can we change its name ?

### ISSUE THREAD

**Issue by JHWen** [yzhangcs/parser#74]
[为什么Windows系统下不能用“con”作为文件名？](https://www.zhihu.com/question/64120639)

**Comment by yzhangcs** [comment]
@JHWen 你好，感谢提出这个问题，之前因为没在Windows上测试因此一直没注意到过.
但是因为没想到比`con`更好的名字，所以近期不打算改了.
现在你可以自己手动clone这个包，改下文件名再本地安装.
