### ISSUE TITLE
ctb7.biaffine.dep.electra问题

### ISSUE THREAD

**Issue by yt-liang** [yzhangcs/parser#83]
想要用ctb7.biaffine.dep.electra来进行依存分析，但是会报如下错误
![image](https://user-images.githubusercontent.com/58623131/135585668-7e5d37a2-c004-428d-a6e0-0efa91a235c9.png)
我自己x把模型下载下来了，如何使用我本地的模型呢

**Comment by yzhangcs** [comment]
@yt-liang Hi, 你好，我想这应该是transformers版本或者本地网络的问题，请去check一下hfl/*对于库版本的要求，然后升级，或者检查一下本地网络是否连接

**Comment by yt-liang** [comment]
还有一个问题，如何使用cuda而不是cpu进行预测，如何修改cuda的device？能同时预测多个吗，predict参数data的形式是怎么样？我进到.py文件，好像没有详细说明data的形式，我想预测多句话

**Comment by yt-liang** [comment]
> @yt-liang Hi, 你好，我想这应该是transformers版本或者本地网络的问题，请去check一下hfl/*对于库版本的要求，然后升级，或者检查一下本地网络是否连接

就是必须要从hfl下载是吗？不能加载本地下载好的

**Comment by yzhangcs** [comment]
@yt-liang 
> 如何使用cuda而不是cpu进行预测，如何修改cuda的device？

cuda预测只要设置一下某个设备可见就可以了，parser会自动使用可见的第一个设备，设备设置可以通过环境变量`CUDA_VISIBLE_DEVICES`
> 能同时预测多个吗，predict参数data的形式是怎么样？
`data`可以是一句话或者多句话的list，或者文件名，具体可以参考`README`的例子

> 就是必须要从hfl下载是吗？不能加载本地下载好的

应该都可以，版本要对

**Comment by yt-liang** [comment]
![image](https://user-images.githubusercontent.com/58623131/135587053-2d5bfce1-6ffa-4d0c-9376-b533aca34041.png)
这样设置CUDA就行吗？如何从本地加载bert呢（我本地已经把electra-180g下载好了）？

**Comment by yzhangcs** [comment]
@yt-liang 环境变量需要在命令行中设置，或者通过`os.environ`.
具体如何加载bert还请参考transformers文档

**Comment by yt-liang** [comment]
> @yt-liang 环境变量需要在命令行中设置，或者通过`os.environ`. 具体如何加载bert还请参考transformers文档

有一次运行成功了electra-180g，之后运行又失败了，运行之后不会把模型下载下来吗？

**Comment by yzhangcs** [comment]
@yt-liang 运行了应该是会下载的
