### ISSUE TITLE
Onnx Conversion

### ISSUE THREAD

**Issue by RobertGengiu** [yzhangcs/parser#84]
Hi,

I have some issues converting a model after training to onnx format. Have you tried to convert a biffine dependency model to onnx for fast inference time?

Thank you!

**Comment by yzhangcs** [comment]
@RobertGengiu Hi, I ran an example command  to convert `biaffine-dep-en` referring to the pytorch docs but failed.
Seems that onnx does not support exporting `PackedSequence` object (pytorch/pytorch#49936)
