### ISSUE TITLE
关于constituency tree数据标注

### ISSUE THREAD

**Issue by geasyheart** [yzhangcs/parser#88]
你好，关于constituency tree标注，从标注上来看：
```
                      TOP                 
                       |                   
                     IP-HLN               
                 ______|________________   
              IP-TPC              |     | 
     ___________|______           |     |  
    |                  VP         |     | 
    |            ______|_____     |     |  
    |         PP-DIR         |    |     | 
    |       ____|______      |    |     |  
NP-PN-SBJ  |           NP    VP NP-SBJ  VP
    |      |           |     |    |     |  
    NR     P           NN    VV   NN    VV
    |      |           |     |    |     |  
    广西     对           外     开放   成绩    斐然

```
它的形式貌似和人正常理解是相反的，比如下面可能会更好：

![123321](https://user-images.githubusercontent.com/11239531/143535834-28e93b8a-7589-4fd5-bf0c-2345661c9328.png)

我的问题在于：

有没有现成的标注工具可以实现类似上图效果，或者说有没有相关的标注工具推荐。

非常感谢！！！

**Comment by yzhangcs** [comment]
@geasyheart Hi，抱歉我对于像这样的标注工具不是很熟悉，所以可能没法给你更多帮助.
据我所知和你上图展示效果比较像的是AllenNLP的[demo](https://demo.allennlp.org/constituency-parsing).
像是这样
<img width="792" alt="image" src="https://user-images.githubusercontent.com/18402347/143543802-83b43312-be69-4a1f-853d-d2661c77fa28.png">

**Comment by geasyheart** [comment]
感谢回复，我先看看。

**Comment by geasyheart** [comment]
我自己写了一个[constituency-tree-labeling-tool](https://github.com/geasyheart/constituency-tree-labeling-tool).
