### ISSUE TITLE
Feature Request: Customizing Stanza Pipeline

### ISSUE THREAD

**Issue by nu11us** [yzhangcs/parser#92]
Is it possible to add the ability to specify parameters in the stanza tokenization pipeline to the API? 

I'd like to do some testing using SuPar with a pretrained Stanza tokenizer like [so](https://stanfordnlp.github.io/stanza/pipeline.html) using the `tokenize_model_path` argument.

**Comment by yzhangcs** [comment]
@nu11us Hi, currently SuPar does not expose the interface of passing args to stanza tokenizer, you can manually modify the code here if you wish.
https://github.com/yzhangcs/parser/blob/33373037ef982e5bbda1c375f29f105f79ec41f5/supar/utils/tokenizer.py#L9-L12

**Comment by nu11us** [comment]
Thank's for the advice, I'll make a fork for that and try it out.
