### ISSUE TITLE
POS tagging

### ISSUE THREAD

**Issue by K-WeiMing** [yzhangcs/parser#94]
Hi,

as noted in the README.md, there is an example provided

```python
con = Parser.load('crf-con-en')
con.predict(['I', 'saw', 'Sarah', 'with', 'a', 'telescope', '.'], verbose=False)[0].pretty_print()
```

I would like to find out how to enable POS tagging in the generated predictions. Thank you.

**Comment by yzhangcs** [comment]
@K-WeiMing Hi, sorry that currently POS tagging is not supported by the released crf parser. POS tags are taken to be indivisible from their corresponding word terminals, and are therefore transparent to parser training.

**Comment by K-WeiMing** [comment]
I've been looking at the code to explore if I can enable the POS tagging within the training / eval / prediction and I'm stuck, it would be great if you can point me in a rough direction on where to look to modify the required lines. Thank you!

**Comment by K-WeiMing** [comment]
Thanks for your quick reply, I will look into the suggested paper. Appreciate it.
