### ISSUE TITLE
parser output token alignment with BERT tokens

### ISSUE THREAD

**Issue by csarron** [yzhangcs/parser#99]
Hi, this is a great library, thanks for the hard work! 

From the demo usage, I wonder if a sentence is tokenized by a BERT tokenizer, is it possible to align the tokens with the SDP parser output? 

Any pointers or suggestions are much appreciated!

**Comment by yzhangcs** [comment]
@csarron Hi,
> From the demo usage, I wonder if a sentence is tokenized by a BERT tokenizer, is it possible to align the tokens with the SDP parser output?

I'm sorry that currently the pretrained models only support word-level parsing.
You might need to modify the input layers to obtain align the tokens with the SDP parser output
